### ISSUE TITLE
Refactor: Defining Programmatically 

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-docs#10]
I try to reproduce this example: https://docs.openrewrite.org/v1beta/refactor#defining-programmatically

I've created new sample project for that: https://github.com/Guseyn/rewrite-java-definitions
I just don't understand how to create properly `Iterable<SourceFile> sources`  and `Iterable<RefactorVisitor<?>> visitors`, so I can get `Collection<Change> changeSet`.

That's how I get `sources`:

```
Iterable<SourceFile> sources = SourceFiles.fromDirectory("src/sample-project");
```

```java
public class SourceFiles {
    public static List<SourceFile> fromDirectory(String sourceDirectory) throws IOException {
        JavaParser javaParser = JavaParser.fromJavaVersion().build();
        List<Path> javaSources = new ArrayList<>(listJavaSources(sourceDirectory));
        return new ArrayList<>(javaParser.parse(javaSources, Paths.get(sourceDirectory)));
    }

    private static List<Path> listJavaSources(String sourceDirectory) throws IOException {
        File sourceDirectoryFile = new File(sourceDirectory);
        if (!sourceDirectoryFile.exists()) {
            return emptyList();
        }
        Path sourceRoot = sourceDirectoryFile.toPath();
            return Files.walk(sourceRoot)
                .filter(f -> !Files.isDirectory(f) && f.toFile().getName().endsWith(".java"))
                .collect(toList());
    }
}
```

And that works, when I use debugger I actually see parsed java structures:

This is how I define `visitors`:

```java
Iterable<RefactorVisitor<?>> visitors = new ArrayList<>(){{
      add(new ImportSet());
 }};
```

```java
public class ImportSet extends JavaRefactorVisitor {
    public J visitClassDecl(J.ClassDecl clazz) {
        maybeAddImport("java.util.Set");
        return super.visitClassDecl(clazz);
    }
}
```

But when I want to get changes:

```java
        Refactor refactor = new Refactor().visit(visitors);
        Collection<Change> changes = refactor.fix(sources);
        for (Change change : changes) {
            Path file = Paths.get("src/sample-project/after").resolve(change.getOriginal().getSourcePath());
            try (BufferedWriter sourceFileWriter = Files.newBufferedWriter(file)) {
                sourceFileWriter.write(change.getFixed().print());
            }
        }
```

size of changes is zero. I think I do something wrong.

It'd be great to see whole example of using java definitions in the code.

**Comment by sambsnyd** [comment]
The reason maybeAddImport wasn't doing anything is that it only adds an import if there's a reference to the type being imported somewhere in the class. This is to avoid adding redundant imports. To add an import regardless of usage, use the AddImport visitor directly.

I've created this PR to your repo demonstrating `AddField` for your reference & consideration.
https://github.com/Guseyn/rewrite-java-definitions/pull/1
