### ISSUE TITLE
Error in AutoFormat docs (and maybe in more sections)

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-docs#11]
`JavaRefactorVisitor` has `visitMethod()` and `visitMethodInvocation()`, seems like `return super.visitMethodDecl(method);` made sense in previous versions of API but not now. 
I think `visitMethod` should be instead in docs.

**Comment by sambsnyd** [comment]
Good catch. Thanks!

**Comment by sambsnyd** [comment]
Fixed in https://github.com/openrewrite/rewrite-docs/commit/244edd792194e01001b261ee76e4aa3850559792
