### ISSUE TITLE
Potentially strip version numbers from Maven guides and recipe command line tabs

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#120]
Noticed today that we're able to run without specifying any version numbers using for instance:

```bash
./mvnw -U  org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:LATEST \
  -DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
```

The `-U` forces a check for the latest plugin when the version number is not specified; wheres `LATEST` seems to correctly resolve the additional dependency. Combined they mean we can probably strip explicit version numbers from (generated) individual recipe pages such as [AssertJ best practices](https://docs.openrewrite.org/reference/recipes/java/testing/assertj/assertj) and guides such as [Migrate to Java 17](https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-to-java-17). This could ensure we no longer have to update as much of the documentation with every release, as those parts of the page can remain unchanged. Also helpful for presentations where version numbers are even further removed from the typical update cycles.

**Comment by mike-solomon** [comment]
Thanks for the suggestion @timtebeek 

I'm trying to understand how this would work and was hoping you might be able to help.

Right now, if I wanted to use Maven to run a recipe such as [AutoFormat](https://docs.openrewrite.org/reference/recipes/java/format/autoformat), I would need to update the `pom.xml` file to look something like: 

```xml
<plugin>
      <groupId>org.openrewrite.maven</groupId>
      <artifactId>rewrite-maven-plugin</artifactId>
      <version>4.39.0</version>
      <configuration>
          <activeRecipes>
              <recipe>org.openrewrite.java.format.AutoFormat</recipe>
          </activeRecipes>
      </configuration>
</plugin>
```

I can't update the `<version>` line to look like `<version>LATEST</version>` as I get an error about invalid versions if I do so.

I presume that something would need to change with our `run` task or there's some other configuration that would need to happen. When I tried to manually change the settings in IntelliJ, it immediately reverted to not having the `-U` flag. 

What do you envision this would look like for a user? What would their `pom.xml` look like and would they need to update their run configurations or would that need to happen elsewhere?

Note that I'm not familiar with Maven so it's possible I'm just missing something obvious here :)

**Comment by timtebeek** [comment]
Ah sorry; reading back it appears I wasn't clear on this only affecting the generated "Maven Command Line" tab of individual recipes. A screenshot as a refresher of this [AssertJ best practices recipe page](https://docs.openrewrite.org/reference/recipes/java/testing/assertj/assertj).

![image](https://user-images.githubusercontent.com/1027334/216163392-e2ccd193-0f0a-42d6-9924-90682526399a.png)

Right now that page lists the full Maven plugin GAV:goal and an explicit version number for the `recipeArtifactCoordinates`:
```bash
mvn org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.33.0 \
  -DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
```

What I'm proposing here is instead to use a versionless variant of the same command:
```bash
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:LATEST \
  -DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
```

So all together the change would come out to:
```diff
- mvn org.openrewrite.maven:rewrite-maven-plugin:4.39.0:run \
+ mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
-  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:1.33.0 \
+  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:LATEST \
   -DactiveRecipes=org.openrewrite.java.testing.assertj.Assertj
```

That command line works just as well, and does not need to be updated whenever a new version comes out.

So it would come down to changing the markdown generator on those specific lines to not use a version variable
[line 879](https://github.com/openrewrite/rewrite-recipe-markdown-generator/blob/main/src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt#L879) and [952](https://github.com/openrewrite/rewrite-recipe-markdown-generator/blob/main/src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt#L952) presently.

**Comment by timtebeek** [comment]
Not sure if or how we can do the same for those that still edit their pom.xml files; as you've already found there might be issues there.

**Comment by mike-solomon** [comment]
Ahh okay, that makes much more sense. Thank you for clarifying :)
