### ISSUE TITLE
Document the new `classPathFromResources` with bundled jars

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#124]
As [reported on Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1675097259855829) there was a bit of confusion on how (and when) best to use the new `classpathFromResources` to setup a recipe test classpath. So far the best documentation to that is in private Slack threads [one](https://moderneinc.slack.com/archives/C01VADFPJQZ/p1674576044031909) and [two](https://moderneinc.slack.com/archives/C01VADFPJQZ/p1674804578685159).

**Comment by mike-solomon** [comment]
Another useful thread to add to this list: [thread](https://rewriteoss.slack.com/archives/C01A843MWG5/p1675929089785139?thread_ts=1675894219.267039&cid=C01A843MWG5).

**Comment by mike-solomon** [comment]
Want to double-check my understanding of `classPathFromResources`. @sambsnyd @timtebeek - would one of you mind double-checking that the below information is correct? I can then clean this up and make a doc for it.

## The problem

If a recipe needs more than two versions of a library, it is can be confusing on how to set that up so tests can run correctly. This is common with migration recipes that span multiple versions. 

Let's consider a recipe that migrates something from Java 11 to 15, but along the way breaks it up into `Java 11 -> 12` and `Java 12 -> 13` and so on. The recipe itself will produce code that is Java 15 code. The tests, however, might expect code to be Java 11 or 12 or 13 or 14, though. If you specify multiple dependencies on different versions in your build files, only the top one will be used. 

This can cause people to struggle to get the appropriate libraries configured for specific tests. Please note, though, that this is only an issue when the tests need many different versions in them. If the tests only need one version, then using `classPathFromResources` doesn't have much use (?)

## The solution

The rewrite recipe library now offers some new functionality to assist with this. It will look in the `META-INF` folder for dependencies. Many different versions of the same dependency can be included in there. Your code can then specify exact versions to run for a particular test. 

For instance, if you wanted to specify that one test should use `assertj-core-3.24.2`, you could add this to your spec:

```java
spec
    .parser(JavaParser.fromJavaVersion()
        .classpathFromResources("assertj-core-3.24.2")
```

This would look in the `META-INF` folder for an `assertj-core-3.24.2` directory and use it accordingly.

To further help make developer's lives easier, new functionality has been added to build files. In `build.gradle` files, you can add a `recipeDependencies` section and specify specific versions in there. This will then be automatically pulled in via the rewrite recipe library to the `META-INF` folder for you.

In the `build.gradle` file this would look like:

```groovy
recipeDependencies {
    parserClasspath("org.assertj:assertj-core:3.24.2")
}
```

**Comment by timtebeek** [comment]
I would maybe not use `something from Java 11 to 15` as an example, since we're not really putting different versions of Java on the classpath here through that mechanism. I think an illustrative use case here is where you have versions 2, 3 & 4 of a library, such as Mockito (maybe not exactly Mockito, but at least a library), and then a deprecation in version 2, removal in version 3, and new additions in 4. Modules that want recipes both for the 2 -> 3 removal and 3 -> 4 additions would otherwise not be able to have the corresponding classes on the classpath without this mechanism. I hope that's clear~ish.

**Comment by mike-solomon** [comment]
Makes sense! Will keep that in mind when I write the full doc.

**Comment by mike-solomon** [comment]
Open questions that I'll need to figure out / get answers for before I can finish the doc:

1. What is the rewrite recipe library? Is that a new thing? Where would someone go to find out about it? Does it serve any point other than adding `recipeDependencies` and `parseClasspath` functionality to build files?
2. How do you configure the recipe library for use in your project? Is it as simple as applying the plugin in your `build.gradle` file and then using `JavaParser.Builder` to load the resources? Or is there anything else that needs to be done?
3. Can Maven projects also use the recipe library? If so, do we have any examples of what that looks like?
4. Does this special configuration of adding multiple versions of the same library serve a point for projects that do not need 3 or more versions of the same library?

**Comment by sambsnyd** [comment]
1. The rewrite recipe library is built from [this repository](https://github.com/openrewrite/rewrite-build-gradle-plugin) and published to the gradle plugin portal. It is not at all required for recipe development, but it collects our conventions for building a recipe module. And provides the `recipeDependencies` and `parseClasspath` functionality.
2. After applying the plugin, users can manually run `downloadRecipeDependencies` which will download the `parserClasspath` jars into the src/main/resources/META-INF.rewrite. Jars can also be placed here manually, using the task or our build plugin are not necessary, it just facilitates populating this folder
3. No. If anyone is using Maven they can put the jars they want into that folder directly. 
4. Not required for projects that don't need to interact with multiple versions of a library.
