### ISSUE TITLE
Announce OpenRewrite releases through socials such as Twitter

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#125]
We have https://twitter.com/openrewrite, which could announce any new notable features & recipes to get some more interaction going there. I quite like how [JReleaser](https://github.com/jreleaser/jreleaser) does their announcements; here's [a recent example](https://twitter.com/jreleaser/status/1608498022295519234?cxt=HHwWhIC-jbubxNIsAAAA) showing a thread of updates.

**Comment by aalmiray** [comment]
FWIW that Twitter thread was generated based on a template https://github.com/jreleaser/jreleaser/blob/v1.4.0/src/jreleaser/twitter.tpl

You may also use the tool to announce to Mastodon https://github.com/jreleaser/jreleaser/blob/v1.4.0/src/jreleaser/mastodon.tpl

Here's the relevant configuration https://github.com/jreleaser/jreleaser/blob/b977b66baed1e4761af054c5d747a0804f457252/jreleaser.yml#L125-L132

What's left is configure secrets required by each announcer

 - https://jreleaser.org/guide/latest/reference/announce/twitter.html
 - https://jreleaser.org/guide/latest/reference/announce/mastodon.html

**Comment by timtebeek** [comment]
Awesome, thank you for the helpful pointers! I think the biggest challenge right now is recovering the Twitter credentials 😅  Any luck there @sambsnyd ?

**Comment by aalmiray** [comment]
FWIW you need a Twitter account with access to the v1 REST API. This type of access is no longer granted by default but you can ask for it. In the future we'll support v2.

**Comment by aalmiray** [comment]
Moreover, you could also post release announcements to Slack & Discord, using  custom templates as well.

**Comment by timtebeek** [comment]
That would indeed fit in great with the platforms we already have, which unfortunately for now are manual steps. We can and should do better. :)

**Comment by mike-solomon** [comment]
A few things need to be decided for this issue:

1. Where do we want to post? Is it in the `General` channels in Slack and Discord? An `Announcements` channel? Something else? Also, I'm unsure whether or not Twitter is even viable with the latest API changes but, if it is, do we want to post there, too?
2. What do we want to post? Just that a new release has happened and a link to it? Or do we want more information?
3. What releases should we make announcements for? Is it just OpenRewrite? What about the BOM? Any other modules?

Once we've decided those things we can figure out a path to add this. I've asked these questions in the internal Moderne Slack to see if anyone has any thoughts on these. Also open to feedback here if anyone has any opinions.

**Comment by mike-solomon** [comment]
My general suggestion for the above questions:

* I think we should post the OpenRewrite and BOM releases in the General channel in the Slack and Discord. If we want to add releases for other modules, that should happen in a separate channel. My thinking is that those OpenRewrite and the BOM are much more important and encompassing and wouldn't be as spammy.
* I think we should include the version number being released and a link to the release page in GitHub. While it might be nice to try and include a changelog or other things, I don't think that's practical as we very rarely have a clean changelog for releases of any of these repos before the release happens. We could potentially add more information in the future.

**Comment by aalmiray** [comment]
As an external spectator, may I suggest adopting a format for commit messages (if you have not done so already). I used my own until I found https://www.conventionalcommits.org/en/v1.0.0/ 

One (great) side effect of adopting commit message conventions (n my case CC) is thinking twice on what the current unit of work does. If the message is too big perhaps the work is too big as well and needs to be split in smaller units. Formatted messages also make it easier to go back in history and remember the context of a given commit.

Of course, formats also allow changelog generators (such as JReleaser) to create release notes based on templates.

**Comment by timtebeek** [comment]
Appreciate the suggestion! We're at the stage where _half_ the company uses those, but only for internal work, whereas for the OSS repositories we have not yet adopted the same. Definitely something to reconsider going forward.

**Comment by mike-solomon** [comment]
Releases have been changed to broadcast into a `#releases` channel in both Slack and Discord now. The tool I'm using (Zapier) _could_ broadcast to Twitter, but that would cost money ($49/month) and I don't think that's particularly worth it. Closing this as resolved.
