### ISSUE TITLE
Document how to consume snapshot versions from the snapshot pages

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#126]
Quite like that we now have snapshots listed in the documentation: https://docs.openrewrite.org/changelog/snapshot-2023-01-30

Next question that came to my mind seeing those is: how would I consume those as a user? 
Is there a BOM published to a snapshot repository that I can use? Likely yes, but documentation could help. :)

**Comment by mike-solomon** [comment]
Thanks for the suggestion! 

To document what I think needs to happen:
* Add a Gradle section that:
  * Specifies how to update the `repositories` section to add a `maven` configuration that points to a `url` of "https://oss.sonatype.org/content/repositories/snapshots/" (which contains the snapshots)
  * Specifies how to update their recipe versions (by using `latest.integration` or a specific version). For instance: `(platform("org.openrewrite:rewrite-bom:latest.integration"))`
* Add a Maven section that:
  * Does something similar as the Gradle section (have to figure out what that is). Important to keep in mind that `latest.integration` doesn't work for Maven. 
  
Will need to figure out if we can grab version numbers in the markdown generator to add to this. Also need to figure out where to put this. For instance, should this be added at the bottom of every snapshot changelog? Should it be its own standalone doc? Something else?

**Comment by mike-solomon** [comment]
Updated markdown generator to add a link to this doc: https://github.com/openrewrite/rewrite-recipe-markdown-generator/pull/42

With that this should be all done :)
