### ISSUE TITLE
Change method name

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-docs#13]
In this example https://docs.openrewrite.org/java/refactoring-java-source-code/changemethodname I get exception: `NoSuchMethodError`. I use proper packages in definition, but it does not work anyway.

Only when I use following "before and after" it works fine:

```java
// before
package org.openrewrite.before;

public class E  {
    void foo() {
    }
}

//after
package org.openrewrite.after;

public class E  {
    void bar() {
    }
}
```

with changed definition
```java
        ChangeMethodName cmn = new ChangeMethodName();
        cmn.setMethod("org.openrewrite.before.E foo()");
        cmn.setName("bar");
        RefactorProcessor.run(cmn, "E.java");
```

As far as I understand it's java parser error.

**Comment by sambsnyd** [comment]
I believe this is fixed. ChangeMethodNameExample from your rewrite-java-definitions project works for me. I remember talking about this with you in another issue that I believe we resolved there. Let me know if there's still any problem with this example.
