### ISSUE TITLE
Fully document declarative YAML recipe format

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-docs#132]
The declarative YAML recipe format is currently documented at https://docs.openrewrite.org/reference/yaml-format-reference. There are however some important features missing there. Most notably the applicability tests (for Java described at https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices#use-applicability-tests) are not documented there.

In addition to documenting them on the mentioned page it may also make sense to add a reference from the section https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices#use-applicability-tests to this page.

**Comment by mike-solomon** [comment]
As part of doing this, it would be swell if we had a schema to share such as suggested by @knutwannheden in [this Slack thread](https://rewriteoss.slack.com/archives/C01A843MWG5/p1675971507077329). A schema like that would also make it easier to write a more complete doc.

**Comment by knutwannheden** [comment]
See also openrewrite/rewrite#2823

**Comment by mike-solomon** [comment]
Docs have been updated to address this. I'll add a link to the schema once that's merged in. Thanks for making this issue!

**Comment by mike-solomon** [comment]
I've updated the doc to link to the schema that was merged in as well.
