### ISSUE TITLE
Show text recipes in Recipe catalog, and potentially document their use on a separate page

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#133]
[Came up in Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1675855590882459?thread_ts=1675780454.761369&cid=C01A843MWG5), as part of a [discussion on Dockerfile search & replace](https://github.com/openrewrite/rewrite-migrate-java/issues/183).
> quick question regarding that FindAndReplace recipe: the recipe is not listed in the [recipe catalog](https://docs.openrewrite.org/reference/recipes) and the same applies for the other recipes in the [text package](https://github.com/openrewrite/rewrite/tree/v7.35.0/rewrite-core/src/main/java/org/openrewrite/text). Is that because they are still in an incubation status or is their usage even discouraged?

It appears these are [filtered out in the recipe markdown generator](https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/912d678e151afefe15df0f6acc8feb3f438cebe3#diff-e4b8582dd50433489f974ba78326a15388206e6b81fe6e4f32ebc62d5420fe23R79), since June 2021, with the change at the time by @sambsnyd . Any insights on if we should keep filtering these recipes Sam? Can/should they be more easily discovered for use in rewrite.yml for instance?

If these recipes are fine to use we might as well document some cases of common text migrations, such as in markdown READMEs and Dockerfiles, preferably with links to their actual use in rewrite modules.

**Comment by timtebeek** [comment]
Done: https://docs.openrewrite.org/recipes/text
Fixed in https://github.com/openrewrite/rewrite-recipe-markdown-generator/pull/50

**Comment by timtebeek** [comment]
We could still add a dedicated Guide to replacing for instance a value in a Dockerfile. Should we reopen this ticket for that @mike-solomon ?

**Comment by mike-solomon** [comment]
I would make a new ticket for that if you don't mind @timtebeek
