### ISSUE TITLE
Add a hint on how to insert type references

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-docs#137]
While the documentation on `JavaTemplate` is already quite good, I think it could be helpful to have a note regarding type references in templates. The user may be inclined to use a _typed substitution indicator_ rather than an _untyped substitution indicator_, since a Java type reference could be thought of as a typed construct. So the user may for instance want to declare a variable using a type cast in the initializer using a template like `#{any()} s = (#{any()}) #{any()};` and then provide a `TypedTree` or similar as the parameter for the first indicator. While in fact the type should either appear as a literal in the template (e.g. `String s = (String) #{any()};`) or alternatively use an untyped indicator (as in `#{} s = (#{}) #{any()};`) and then substitute these indicators for Strings representing the qualified (or unqualified) type name.

See also https://github.com/openrewrite/rewrite/issues/2817

**Comment by mike-solomon** [comment]
@knutwannheden Do you know if this still applies with the latest `JavaTemplate` / OpenRewrite updates? I know a lot has changed on that front.

**Comment by knutwannheden** [comment]
@mike-solomon Thanks for checking. Yes, this is still the case now.

**Comment by knutwannheden** [comment]
The typed indicators are those which look like `#{any()}` and the untyped ones are the `#{}` ones. And when inserting a type reference like `String` or `int` one may think that the typed ones are the correct ones, whereas this requires the untyped ones, because `String` is a syntactic construct and not a valid Java expression.

**Comment by knutwannheden** [comment]
For now I think we can maybe just close this issue. I read through the documentation we have and I am afraid that adding another hint / warning to the section on _typed substitution indicators_ would just confuse the reader.

However, since we in the current documentation don't mention the difference between context-free and -sensitive (only in the [8.1.2 release notes](https://docs.openrewrite.org/changelog/8-1-2-release#javatemplate-api-has-been-updated)), I feel like an overhaul is required.

@mike-solomon Feel free to close this for now and I will be happy to review the overhaul of the documentation at some point in the future.

**Comment by mike-solomon** [comment]
Sure that would be appreciated @knutwannheden
