### ISSUE TITLE
Expand upon current IDE setup instructions

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#138]
We already have a few places where we describe how to best tune your local environment and IDE for recipe development:
 - https://github.com/openrewrite/rewrite/blob/main/CONTRIBUTING.md
 - https://docs.openrewrite.org/authoring-recipes/recipe-development-environment
 - https://docs.openrewrite.org/reference/building-openrewrite-from-source

Yet we can possibly do more to lower the barrier for entry into development. Two questions that came up on my end for instance:
1. When I execute the tests, there is a noticeable delay before the tests start executing, possibly related to resolving latest.release dependencies. What can be done (and documented) to prevent that?
2. When a recipe does not produce the expected diff, the expected and actual values are printed to the console by default. How to open a dialog for easier visual comparison?

Possibly there will be more such questions for people just getting started, and it would be good to ensure those are resolved to create a smooth recipe development experience.

**Comment by timtebeek** [comment]
Could be worth documenting the toggle to `Run tests using: IntelliJ` rather than Gradle for both a speed up and easier result comparison.
![image](https://user-images.githubusercontent.com/1027334/221169559-ae0e5efa-4547-47e0-a71c-338aa004c4ed.png)

**Comment by mike-solomon** [comment]
I believe _most_ of these things have been addressed. However, I'm not sure about this part:

> When I execute the tests, there is a noticeable delay before the tests start executing, possibly related to resolving latest.release dependencies. What can be done (and documented) to prevent that?

Is there anything that can be done for that @timtebeek ? Is that just part of running the tests with IntelliJ or is there something else that can be done?

**Comment by timtebeek** [comment]
That is needed part of running the tests through IntelliJ, thanks! I agree that this issue can be closed. :)
