### ISSUE TITLE
Make composite recipes stand out visually in recipe catalog listing

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#139]
When looking through the recipe catalog, one currently sees a list per category, and it's not immediately clear which recipes contain other recipes, and are thus the more likely ones you'd want to run. Take for example the [junit5 category of recipes](https://docs.openrewrite.org/reference/recipes/java/testing/junit5).

![image](https://user-images.githubusercontent.com/1027334/218505456-547eb999-c925-44ba-81a8-87311248a69e.png)

There's a number of different recipes, all of which seem to related to migrating JUnit 4 to JUnit JUpiter, but it's not immediately clear if you should run those individually, or if there's an aggregation recipe that includes some others. Even a little 🗃️  icon or something similar could help the aggregation recipe such as [Best practices](https://docs.openrewrite.org/reference/recipes/java/testing/junit5/junit5bestpractices) and [Jupiter migration](https://docs.openrewrite.org/reference/recipes/java/testing/junit5/junit4to5migration) stand out just a bit more.

**Comment by timtebeek** [comment]
This also came up as feedback from the team at a Dutch bank trying out OpenRewrite for use there.

**Comment by timtebeek** [comment]
@kmccarp suggested to also show, for individual recipes, if they are contained in composite recipes. Should help discoverability and gently guide towards running the composites rather than the individual recipes.

**Comment by mike-solomon** [comment]
[Right now](https://moderneinc.slack.com/archives/C01VADFPJQZ/p1687800092346189?thread_ts=1687800062.411859&cid=C01VADFPJQZ), a recipe can't know whether or not it is contained in a composite recipe -- although it sounds like this could change eventually.
