### ISSUE TITLE
Document supported languages on docs.openrewrite.org

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#141]
We had a question come in on Slack:

> Hi, What other languages does OpenRewrite work with?

Which intuitively at first seemed strange; as "we all know" what languages we support.
Yet it's not listed explicitly in the documentation anywhere, and could be helpful to add.

The answer given was:
```
We have support for:
Programming languages:
-  Java
-  Groovy/Gradle - Focus is on supporting Gradle dependency manipulation, but works on most regular groovy sources as well
-  Kotlin - Early support has been released, but it is quite new, still being actively developed and not widely tested
-  Python - Not yet released. In development
-  COBOL - Closed source, commercial feature
Data formats:
-  XML
-  Properties
-  YAML
-  JSON
-  Protobuf
-  Maven POMs, with dependency maanagement
After finishing Kotlin and Python we will next expand into Typescript and C#
```

Putting that on a page somewhere, or even a landing page, could help those that quickly want to evaluate OpenRewrite.

**Comment by mlvandijk** [comment]
For Python, it would be interesting to know how to run those recipes. Currently the documentation is Maven/Gradle (JVM) focussed

**Comment by mlvandijk** [comment]
Also Kotlin is not really (well) represented in the documentation (yet).

**Comment by timtebeek** [comment]
To close this out: the page should start to show on: https://docs.openrewrite.org/reference/supported-languages
