### ISSUE TITLE
Authoring Recipes getting started issues

### ISSUE THREAD

**Issue by lluccia** [openrewrite/rewrite-docs#144]
I recently started studying OpenRewrite for writing some recipes and found some issues in the authoring-recipes getting started guide that can make the developer to have a bad first interaction with the tool.

Following the first 2 guides in sequence (in the maven path, using java 17) do not drive the project to a working state:

- <https://docs.openrewrite.org/authoring-recipes/recipe-development-environment>
- <https://docs.openrewrite.org/authoring-recipes/writing-a-java-refactoring-recipe>

Issues found:

- `SayHelloRecipe` uses lombok annotations, but lombok is not added as dependency in `pom.xml`
- `JsonProperty` and `JsonCreator` annotations are not imported in the code snippet
- `SayHelloRecipeTest` do not compile because they use multiline string
- Tests are not executed using maven build (`mvn test`) - using maven 3.8.7

I did not followed the gradle path, but I think it will also get some of these issues.

Improvements suggestions:

- `SayHelloRecipe` uses lombok annotations, but lombok is not added as dependency in `pom.xml`
  - add lombok dependency in the `pom.xml` snippet on `recipe-development-environment`, or a reference to lombok docs to add it <https://projectlombok.org/setup/maven>

- `JsonProperty` and `JsonCreator` annotations are not imported in the code snippet
  - add the imports to the code snippets
  ```java
  import com.fasterxml.jackson.annotation.JsonCreator;
  import com.fasterxml.jackson.annotation.JsonProperty;
  ```
- `SayHelloRecipeTest` do not compile because they use multiline string
  - add different source/target levels for java code and tests in `pom.xml` properties (I saw that suggestion later in `recipe-testing` doc, but without snippets showing how to do it):
  ```xml
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.testSource>17</maven.compiler.testSource>
    <maven.compiler.testTarget>17</maven.compiler.testTarget>
  </properties>
  ```

- Tests are not executed using maven build (`mvn test`)
  - Junit5 requires surefire-plugin version at minimum 2.22.0 to execute tests (<https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven>), and the default plugin version in maven 3.8.7 is 2.12.4 ([maven 3.8.7 bindings](<https://github.com/apache/maven/blob/maven-3.8.7/maven-core/src/main/resources/META-INF/plexus/default-bindings.xml#L82>))
  - the default surefire version was bumped to 3.0.0-M8 in recently released maven 3.9.0 ([maven 3.9.0 bindings](<https://github.com/apache/maven/blob/maven-3.9.0/maven-core/src/main/resources/META-INF/plexus/default-bindings.xml#L82>))
  - either instruct to use maven >= 3.9.0 or add newer surefire-plugin version to the `pom.xml` snippet
  ```xml
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M9</version>
      </plugin>
    </plugins>
  </build>
  ```

I guess these would give the developer a better onboarding experience.

**Comment by timtebeek** [comment]
Thank you very much for this detailed feedback! Very valid points indeed, and sorry to hear you encountered all these issues. Glad to see you were able to work through them, and kindly provided this feedback here. This will certain improve the experience for the next one to read the documentation!

**Comment by timtebeek** [comment]
I've just applied your suggestions in https://github.com/openrewrite/rewrite-docs/pull/145; Thanks for making them so straightforward to follow! Let me know if you have any other suggestions, and thanks again for taking the time to report these issues here!
