### ISSUE TITLE
Confusion around applicability tests in yaml recipes

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#147]
Our [current documentation around yaml applicability tests](https://github.com/openrewrite/rewrite-docs/blob/master/reference/yaml-format-reference.md#applicability-tests) might contain slight imperfections that lead to confusion in an issue and pull request last week:

1. should `anySource` match when `any` or `all` of the argument recipes match any file?
    https://github.com/openrewrite/rewrite-testing-frameworks/pull/320

2. should `FindSourceFiles` be used to limit applicability to specific files, or should one use `HasSourcePath` instead?
    https://github.com/openrewrite/rewrite/issues/2919

Should be good to clear these up, as they lead to questions and debugging currently.

**Comment by shanman190** [comment]
@timtebeek, the way that this was explained to me was that it is logical `AND` all around.

So to be explicit:
```
applicability:
  anySource:
    - com.example.A
    - com.example.B
```

The above only applies if both are true. If one of them is false, then the recipe does not apply. This works the same for single source and a combination of single source and any source.

**Comment by mike-solomon** [comment]
I'm going to close this ticket as I think this no longer applies. YAML recipes no longer work with applicability tests. If I've misunderstood please let me know and feel free to reopen.
