### ISSUE TITLE
ReorderMethodArgumentsExample typo

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-docs#15]
In this example https://docs.openrewrite.org/java/refactoring-java-source-code/reordermethodarguments#java-definition there is a typo:

```java
ReorderMethodArguments rma = new InsertMethodArgument();
```

It should be fixed to:

```java
ReorderMethodArguments rma = new ReorderMethodArguments();
```

**Comment by sambsnyd** [comment]
Good catch! Thank you. Fixed in https://github.com/openrewrite/rewrite-docs/commit/244edd792194e01001b261ee76e4aa3850559792
