### ISSUE TITLE
Update individual rewrite module READMEs to link to Recipe Catalog / Marketplace

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#156]
Right now some of our individual rewrite module READMEs are pretty barren. Taking [rewrite-github-actions as an example](https://github.com/openrewrite/rewrite-github-actions), it's barely clear what it does from the README.
![image](https://user-images.githubusercontent.com/1027334/227389804-a9823ee0-5d71-4a96-9885-72c26dd14cf9.png)

## Link to the Recipe Catalog
It might be nice to add links to [the respective recipes in the recipe catalog](https://docs.openrewrite.org/reference/recipes/github):
![image](https://user-images.githubusercontent.com/1027334/227389882-c26b9c14-ccd9-454f-812b-870134fb3704.png)

## Link to the Marketplace
Or even a similar link to what we have in the docs to [link to the module recipes in the platform](https://public.moderne.io/marketplace/org.openrewrite.github).
![image](https://user-images.githubusercontent.com/1027334/227389931-49ecf15e-45a0-4d9c-aee5-9cd2bd47e2ef.png)

Would require stable links, but not much maintenance past that, and be a bit gentler on people that come across these module READMEs.

**Comment by mike-solomon** [comment]
@timtebeek I took a look at this this morning and I'm a bit unsure on how to go about this. I took a look at [rewrite-migrate-java](https://github.com/openrewrite/rewrite-migrate-java) for instance - but I have no idea _where_ to link to. There's so many different recipes in the catalog that could be linked to. There's not like a "rewrite-migrate-java" section as far as I see. Likewise, where would I link to in the SaaS?

Maybe it would be alright to just update the READMEs with links to the OpenRewrite recipe catalog? Something generic that could go in each of them such as:

```
For extensive documentation on what recipes exist and how to use them, please check out our <recipe catalog>.

If you want to try and run recipes across thousands of open-source repositories, try <running them on the Moderne SaaS>.
```

**Comment by timtebeek** [comment]
Hmm; indeed it's not a perfect fit for each repository README, but my thought was mostly to keep it specific to the associated repository, even if the links are imperfect. So for instance:

rewrite-testing-frameworks -> https://docs.openrewrite.org/recipes/java/testing
rewrite-spring -> https://docs.openrewrite.org/recipes/java/spring
rewrite-logging-frameworks -> https://docs.openrewrite.org/recipes/java/logging
rewrite-migrate-java -> https://docs.openrewrite.org/recipes/java/migrate

We already have quite some generic links, but someone that stumbles upon one of our repository might be more interested in what that module can do specifically.

Understandable if this is hard to automated, perhaps somewhat fragile, and thus not high priority. Indeed a generic link to the recipe catalog (search?) could serve as a fallback if that's easier.

**Comment by mike-solomon** [comment]
@timtebeek If you want to come up with a list like that for each of the repositories, I'm happy to update them accordingly. If not, I can pursue a more generic approach.

**Comment by timtebeek** [comment]
Sure! there's three pending, but the others I think are good to go.

- [ ] rewrite-circleci -> https://docs.openrewrite.org/recipes/circleci
- [ ] rewrite-cloud-suitability-analyzer -> https://docs.openrewrite.org/recipes/cloudsuitability
- [ ] rewrite-concourse -> https://docs.openrewrite.org/recipes/concourse
- [ ] rewrite-cucumber-jvm -> pending generation
- [ ] rewrite-github-actions -> https://docs.openrewrite.org/recipes/github
- [ ] rewrite-java-security -> https://docs.openrewrite.org/recipes/java/security
- [ ] rewrite-java-dependencies -> https://docs.openrewrite.org/recipes/java/dependencies
- [ ] rewrite-jhipster -> https://docs.openrewrite.org/recipes/java/jhipster
- [ ] rewrite-hibernate -> pending
- [ ] rewrite-kubernetes -> https://docs.openrewrite.org/recipes/kubernetes
- [ ] rewrite-logging-frameworks -> https://docs.openrewrite.org/recipes/java/logging
- [ ] rewrite-micronaut -> https://docs.openrewrite.org/recipes/java/micronaut
- [ ] rewrite-migrate-java -> https://docs.openrewrite.org/recipes/java/migrate
- [ ] rewrite-quarkus -> https://docs.openrewrite.org/recipes/quarkus (inconsistent as compared to micronaut)
- [ ] rewrite-spring -> https://docs.openrewrite.org/recipes/java/spring
- [ ] rewrite-sql -> pending
- [ ] rewrite-static-analysis -> pending? possibly still https://docs.openrewrite.org/recipes/java/cleanup.
- [ ] rewrite-terraform -> https://docs.openrewrite.org/recipes/terraform
- [ ] rewrite-testing-frameworks -> https://docs.openrewrite.org/recipes/java/testing

Since I copied these links mostly from the [recipe catalog hierarchy page](https://docs.openrewrite.org/recipes), I do think there's some way that we could tie these automatically. But then still you'd have to insert them into the individual READMEs, and while that's a fun scripting exercise I'd have done in the past, I'm not sure that's something you'd be up for.

**Comment by mike-solomon** [comment]
Updated what I could of the above. 

Should any of these be included:

* https://github.com/openrewrite/rewrite-recommendations
* https://github.com/openrewrite/rewrite-all
* https://github.com/openrewrite/rewrite-cobol
* https://github.com/openrewrite/rewrite-python
* https://github.com/openrewrite/rewrite-analysis
* https://github.com/openrewrite/rewrite-javascript
* https://github.com/openrewrite/rewrite-kotlin

**Comment by timtebeek** [comment]
Thanks a lot for those updates! There's no need to update those other ones I think.

Would you want to keep this open to close those final pending ones once the new docs are live?

**Comment by mike-solomon** [comment]
If it's alright with you, I'd rather leave this open until those repos are ready to be updated so I don't forget.

**Comment by mike-solomon** [comment]
@timtebeek the docs have been generated - so whenever you have some time to suggest links for the other ones, I'll get the rest updated accordingly.

**Comment by timtebeek** [comment]
Sure!
- [ ] rewrite-cucumber-jvm -> https://docs.openrewrite.org/recipes/cucumber/jvm
- [ ] rewrite-hibernate -> https://docs.openrewrite.org/recipes/hibernate
- [ ] rewrite-sql -> https://docs.openrewrite.org/recipes/sql
- [ ] rewrite-static-analysis -> https://docs.openrewrite.org/recipes/staticanalysis-1

**Comment by mike-solomon** [comment]
Thanks! All repos have been updated. Closing.
