### ISSUE TITLE
Document `Datatables`

### ISSUE THREAD

**Issue by rpau** [openrewrite/rewrite-docs#164]
At this moment there are some important recipes that use datatables, which is an interesting structure to aggregate data in the Moderne platform. 

There is no documentation yet about datatables, which should be a basic OpenRewrite concept.

**Comment by okundzich** [comment]
We need also to improve the recipe documentation generator so that we can see which datatables a recipe produces.

**Comment by mike-solomon** [comment]
I haven't worked with data tables before so will definitely need some assistance from someone else to get a doc added and the markdown generator updated.

**Comment by mike-solomon** [comment]
I started looking into this but it sounds like this feature is only half finished right now. If you make a recipe with a data table and run it locally, you can't actually access or see that table as other plugins haven't been updated. Furthermore, it sounds like testing for the data tables hasn't been fleshed out yet.

I plan on waiting until those things are resolved before working on this issue.

**Comment by mike-solomon** [comment]
To save some of my notes for the future:

When making a Data Table you'll need to:

1. Create a class that extends `DataTable<Row>`
2. The `Row` class is typically defined as a static class inside of your DataTable class.
3. Rows have `@Column` annotated variables. Each column should have a `displayName` and a `description`.

Example Data Table Class:

```java
public class NameOfTable extends DataTable<NameOfTable.Row> {
    public NameOfTale(Recipe recipe) {
        super (recipe,
                "Display name of table",
                "A detailed description of the table."
        )
    }

    @Value
    public static class Row {
        @Column(displayName = "Some name", description = "Some description.")
        String someColumn;

        @Column(displayName = "A different display name", 
                description = "A different description")
        Long someOtherColumn;
    }
} 
```


* [Example recipe](https://github.com/openrewrite/rewrite-java-dependencies/blob/31de00a6c0aaca6cd3be89a374f1af7e72182b42/src/main/java/org/openrewrite/java/dependencies/DependencyList.java#L31)
* [Example test that will change](https://github.com/openrewrite/rewrite-javascript/blob/2626d711f966b8ca7829040d4ec16ea689eb2dbb/src/test/java/org/openrewrite/javascript/search/FindParseFailuresTest.java#L141)

**Comment by mike-solomon** [comment]
related issue for the markdown generator: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/57

**Comment by timtebeek** [comment]
Adding a link here for folks already interested in data tables, as those have been documented for users of Moderne:
https://docs.moderne.io/user-documentation/data-tables
The Moderne CLI, which runs OpenRewrite recipes, also already produces data tables, [as used in `mod study`](https://moderneinc.github.io/moderne-cli/mod-study.html).

Documentation of data tables for OpenRewrite will make sense as soon as we have support in each of the plugins for producing data tables as well, likely using the same format as used in the CLI:
- https://github.com/openrewrite/rewrite-gradle-plugin/issues/201
- https://github.com/openrewrite/rewrite-maven-plugin/issues/555

**Comment by mike-solomon** [comment]
As data tables appear to be more of a moderne feature and there are no plans to update OpenRewrite recipe output to see and use data tables, I'm going to go ahead and close this issue. If that changes in the future, we can explore adding this to the docs.
