### ISSUE TITLE
Create a repository and templates for write access requests 

### ISSUE THREAD

**Issue by rpau** [openrewrite/rewrite-docs#188]
**Background**

Third-party communities might want to transfer their recipe repositories. In this case, they should also have write permissions to the repositories. However, now the repository will be allocated in the openrewrite org.

**Acceptance Criteria**

- [x] There is a new repository for `access-requests`
- [x] There is a template to request write access to the repository for a list of developers.

**Comment by timtebeek** [comment]
Had a quick look at how others handle these sort of requests, for instance [Joining Quarkiverse](https://github.com/quarkiverse/quarkiverse/wiki#joining-quarkiverse) via [extension_proposal.yml](https://github.com/quarkusio/quarkus/blob/main/.github/ISSUE_TEMPLATE/extension_proposal.yml)

We can do something similar; I'm expecting a mix of documentation on https://docs.openrewrite.org, and potentially some duplicate documentation in a README for the new requests repository.

I'm leaning towards a slightly different name for the repository: I want the name to be a call to action, and convey that we both invite contributors, as well as adopt existing repositories such as we did with rewrite-jenkins. With that said I'm leaning towards for instance:

* openrewrite/collaborate

And then within the repository have two issue forms, one to get access to existing repositories, and one for adopting new libraries and frameworks.

We _could_ even have the form to get access just in https://github.com/openrewrite/.github/tree/main/.github/ISSUE_TEMPLATE ; that way the form is available on every repository, and not hidden away in a different access repository. Should also help scale up such requests and immediately have the applicable people involved in that project.

**Comment by timtebeek** [comment]
So two forms added:
1. https://github.com/openrewrite/.github/pull/7 for write access to each existing repository
2. https://github.com/openrewrite/collaboration-proposals/pull/1 to propose collaborations

We'll likely also want to document the community and governance over on docs.openrewrite.org, and call out those two forms in a similar manner to [what we've seen for Quarkiverse](https://quarkus.io/blog/quarkiverse/).

**Comment by mike-solomon** [comment]
@timtebeek No rush - just curious about the status of this. Does more work need to be done on this end? Is this blocked on anything in particular?

**Comment by timtebeek** [comment]
The tasks laid out at the start of this issue are covered, but we do not yet refer to these forms from a "community" landing page in the OpenRewrite docs. We're also adding a community page to the moderne.io website, which might also feature links to these forms, but it's not exactly clear where to draw the line.

Maybe best to close this issue and ask internally on thoughts of similarly adding a community page to the OpenRewrite docs, and linking to [the collaboration proposal form](https://github.com/openrewrite/collaboration-proposals/issues/new/choose) from there.

**Comment by mike-solomon** [comment]
Gonna close this issue as I think this isn't being worked on anymore. Feel free to reopen if you feel like it is.
