### ISSUE TITLE
Change maven plugin documentation to suggest adding recipe dependencies to plugin dependencies rather than provided scope.

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-docs#20]

**Comment by okundzich** [comment]
The whole maven plugin documentation needs to be updated. It will become part of the reference material in 7.x. Please merge the work in progress there on this particular issue.

https://app.gitbook.com/@openrewrite/s/openrewrite/rewrite-7/reference-1/maven/rewrite-maven-plugin

**Comment by pway99** [comment]
commit associated with this work  https://github.com/openrewrite/rewrite-docs/commit/dc870d7689994109e37cd62576351204b7eb5611
