### ISSUE TITLE
Missing parameter in classpathFromResources

### ISSUE THREAD

**Issue by joanvr** [openrewrite/rewrite-docs#204]
In this page: https://github.com/openrewrite/rewrite-docs/blob/4278bcf2cb0c5b401e58f3e8e6aa71f273c90d50/authoring-recipes/multiple-versions.md
we are referring to the method `classpathFromResources`, but it's missing the first parameter (ExecutionContext)
However, it's not super clear to me now, how this ExecutionContext could be gathered there, because the obvious thing of `spec.getRecipeExecutionContext()` seems to be always null at this point...

A `new InMemoryExecutionContext()` should do the trick, because actually it's only using the execution context to retrieve a config and the default one is good enough for an example in the docs.

**Comment by mike-solomon** [comment]
The doc linked above has the `new InMemoryExecutionContext()` as the first parameter so I'm guessing this is no longer an issue. Closing.
