### ISSUE TITLE
Docs: Getting Started Java and Maven

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#21]
https://app.gitbook.com/@openrewrite/s/openrewrite/rewrite-7/getting-started/getting-started-java-and-maven

Audience: New to rewrite
Goal: Learn by doing
Outcomes:
- Clone sample project or use their own
- Configure everything they need: IDE, plugins, dependencies, https://github.com/openrewrite/rewrite point to prerequisites here
- Get familiar with the rewrite core recipes, plugin commands, yaml syntax, activate recipes, execute, see diffs, etc.

Follow up tutorials and guides will assume this base level of knowledge of rewrite, project configuration etc. 

Also some material here 
https://app.gitbook.com/@openrewrite/s/openrewrite/rewrite-7/reference-1/maven/rewrite-maven-plugin
https://app.gitbook.com/@openrewrite/s/openrewrite/getting-started/rewrite-gradle-plugin

**Comment by okundzich** [comment]
https://app.gitbook.com/@openrewrite/s/openrewrite/rewrite-7/tutorials-and-guides/modifying-methods-with-javatemplate

Project setup and What you need sections start to repeat across guides, can we move it to getting started and only have versions of dependencies in guides?

**Comment by sambsnyd** [comment]
Maven plugin getting started in this commit: https://github.com/openrewrite/rewrite-docs/commit/723070cfe756afdd4c5a35ec1061e50401e62c38

Gradle equivalent coming shortly.

**Comment by sambsnyd** [comment]
I've closed issue #35 since I've merged that contet back into this document.
This is now ready for review for Gradle and Maven getting started instructions: https://docs.openrewrite.org/rewrite-7/getting-started
