### ISSUE TITLE
Missing document examples for some recipes

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#210]
Yaml Change Key as an example; there's [a test annotated with DocumementExample](https://github.com/openrewrite/rewrite/blob/c75ead0ed463b9df751c3d15ab3126f1d373f998/rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangeKeyTest.java#L47), yet there's no example shown in the docs at https://docs.openrewrite.org/recipes/yaml/changekey

**Comment by mike-solomon** [comment]
@kunli2 Might have more context into this.

**Comment by kunli2** [comment]
this issue has the same root cause as https://github.com/openrewrite/rewrite-docs/issues/211
fixed.
we will need to release doc.

**Comment by mike-solomon** [comment]
This should be resolved once the next version of OpenRewrite is released and we re-generate the docs. Leaving as blocked until the next release happens.

**Comment by mike-solomon** [comment]
This is blocked on the same issue as https://github.com/openrewrite/rewrite-docs/issues/211

[See Tim's message for more details](https://github.com/openrewrite/rewrite-docs/issues/211#issuecomment-1668034849)

**Comment by timtebeek** [comment]
Let's continue this in
- https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/74#issuecomment-2293912458
