### ISSUE TITLE
Update popular recipe guide to upgrade to Micronaut 4

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#217]
## What problem are you trying to solve?
A couple of pages still refer to upgrading to Micronaut 3, whereas Micronaut 4 was released on July 14th, with good migration support through helps from the Micronaut team.
https://github.com/openrewrite/rewrite-docs/blob/master/running-recipes/running-recipes.md
https://github.com/openrewrite/rewrite-docs/blob/master/running-recipes/popular-recipe-guides/migrate-to-micronaut-3-from-micronaut-2.md

## Describe the solution you'd like
Update these references to refer to https://docs.openrewrite.org/recipes/java/micronaut/micronaut3to4migration
Possibly incorporating some of the documentation steps seen at:
https://micronaut.io/2023/07/14/upgrade-to-micronaut-framework-4-with-openrewrite-and-gradle/
https://micronaut.io/2023/07/14/upgrade-to-micronaut-framework-4-with-openrewrite-and-maven/

**Comment by mike-solomon** [comment]
Do you think it's worth making a new guide of going from 3 to 4 or can people use these same recipes to go from 2 to 4? I'm wondering if this is a situation where people would search for "Update to Micronaut 3" and then be confused when we don't have that.

Also - do you know where we could find examples of what these recipes do? In looking over the existing guide, we have some examples of how the code might change -- but I didn't see any examples in the Micronaut links. I'm not sure if those are still applicable for the Micronaut 4 upgrade or if they should be removed or something else.

**Comment by timtebeek** [comment]
Probably a new guide only for 3 to 4 makes sense, since we don't currently chain the 2->3 migration into the 3->4 migration, and I'm not sure if that's safe to do so now. We can leave the 2 -> 3 migration guide as it is, and add a note at the top to both to cross reference them.

And perhaps a reference to this blog, and/or some of the information in there could help.
https://www.moderne.io/blog/micronaut-framework-4-0-automated-upgrade-with-openrewrite

**Comment by mike-solomon** [comment]
Thanks for the clarification @timtebeek !

I think for this guide to be effective we'll need some samples of what this recipe changes. Do you know if there is a sample repository similar to the spring petclinic one where we could run this recipe and see what changes so I could get some real-world examples?

If not, are there any parts of the recipe that you think are especially important to call out? Perhaps we can use the tests to show a before and after for some of those? (see the below photo for options)

![image](https://github.com/openrewrite/rewrite-docs/assets/1187834/5b8561a6-31c6-4dc5-afd5-49b98c0bf0f6)

If you aren't sure of any of these, any idea if anyone on the team would know more about this?

**Comment by timtebeek** [comment]
So since I didn't know any good samples by heart, what I've instead done is have a bit of fun with ingesting the Micronaut Guides for v3 into the platform, and running our automated migration guides on those. Here are some temporary results: https://app.moderne.io/results/JRLm9
You can recreate these if needed, running [Micronaut3to4Migration](https://app.moderne.io/recipes/org.openrewrite.java.micronaut.Micronaut3to4Migration) against [micronaut-guides-mn3](https://app.moderne.io/organizations/micronaut-projects/micronaut-guides-mn3?branch=master&origin=github.com).

That demonstrates the effect the recipes would have on their v3 guides, as they are migrated to v4, which you should be able to correlate to the recipes using the top right action on any diff.
![image](https://github.com/openrewrite/rewrite-docs/assets/1027334/bf3c96f6-c9e5-46eb-a736-9e8520f7b1b4)

Hope that helps! It sure was fun to explore in this way. :)

**Comment by timtebeek** [comment]
Alternatively you can look through these manual changes they did to update their guides:
https://github.com/micronaut-projects/micronaut-guides/commit/deda4ae09119315906495bc38abd62b079e8e05a
Just has the slight risk that not all of those changes we currently support with recipes, so be sure to check & screenshot selectively. 🙃
