### ISSUE TITLE
Docs: Concepts and Explanations

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#22]
https://app.gitbook.com/@openrewrite/s/openrewrite/rewrite-7/concepts-and-explanations

Freeform explanation of core concepts of Rewrite for people who either want to learn about rewrite to make use of existing recipes or create new ones.

- [x] Recipes (Ready for Review)
- [x] Visitors (Ready for Review)
- [x] Environment (Ready for Review)
- [x] Styles (Ready for Review)
- [x] JavaTemplate (Ready for Reivew)

**Comment by sambsnyd** [comment]
All of the concepts and explanations now have an entry. Most recently I created one for Markers. They are ready for review.
https://docs.openrewrite.org/v1beta/markers
