### ISSUE TITLE
Supported languages are undiscoverable

### ISSUE THREAD

**Issue by andrewpollock** [openrewrite/rewrite-docs#233]
## What version of OpenRewrite are you using?

I'm not, I just learned about it at a conference presentation and wanted to learn more about capabilities 

## How are you running OpenRewrite?

I'm not, I just learned about it at a conference presentation and wanted to learn more about capabilities 

## What is the smallest, simplest way to reproduce the problem?

Find someone who has never heard of this software. Point them at the documentation (optionally on a mobile device). Ask them to answer the question "what languages are supported by OpenRewrite?" in 30 seconds.

## What did you expect to see?

Some sort of easily discoverable enumeration of supported languages.

## What did you see instead?

Nothing obvious (to me). Not even an FAQ.

## What is the full stack trace of any errors you 

N/A

## Are you interested in contributing a fix?

Happy to review a PR

**Comment by timtebeek** [comment]
Hi @andrewpollock ! Thanks for your suggestion to document the supported languages in the OpenRewrite docs as well. It's true that these aren't explicitly listed for now, although there's hints as to what's supported in [the recipe catalog](https://docs.openrewrite.org/recipes). Support is evolving fast, but perhaps not so fast the docs can't keep up. :)

We did document our current support and future plans in terms of language support over on https://docs.moderne.io/references/supported-languages
& https://docs.moderne.io/references/language-roadmap
Perhaps we can feature some of the same information in these docs as well.

Hope the above links already help; I'll ask @mike-solomon if he can work in a similar section in the docs here.

Out of curiosity: what conference presentation did you watch that brought you here? :)

**Comment by andrewpollock** [comment]
> Out of curiosity: what conference presentation did you watch that brought you here? :)

I'm live filing from "Scaling the Security Researcher to Eliminate OSS Security Vulnerabilities Once and For All - Jonathan Leitschuh, Open Source Security Foundation" at OSS EU

**Comment by mike-solomon** [comment]
Thanks for the suggestion! I've gone ahead and added this. You should see it available in a few minutes once the deploy finished.

**Comment by JLLeitschuh** [comment]
👋 This talk still has legs it seems! 😂🙂
