### ISSUE TITLE
Consolidate/link building OpenRewrite docs

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-docs#238]
As [reported in our community Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1697642466805919?thread_ts=1697093754.874509&cid=C01A843MWG5), we have a variety of docs that talk about how to build OpenRewrite. They're scattered around and contain different types of information.

* https://docs.openrewrite.org/reference/building-openrewrite-from-source
* https://docs.openrewrite.org/authoring-recipes/recipe-development-environment
* https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#optimizing-your-ide-for-only-modules-you-want-to-work-on

We should go through these and determine:
* Do we need each of those docs
* How can these be connected
* If there's any information that's wrong or missing

**Comment by timtebeek** [comment]
Even though I suggested we open an issue, I failed to remember I'd already opened such an issue previously;
- https://github.com/openrewrite/rewrite-docs/issues/138

Linking that here such that we can close both issues once we consolidate the docs. 😅

**Comment by mike-solomon** [comment]
I:

* Update our [building and developing OpenRewrite doc](https://docs.openrewrite.org/reference/building-openrewrite-from-source) to including all the information that was in the [CONTRIBUTING.md](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md) file
* Linked to the above doc from the [recipe development environment doc](https://docs.openrewrite.org/authoring-recipes/recipe-development-environment)
* Update the [CONTRIBUTING.md doc](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md) to point to the OpenRewrite doc for building and developing OpenRewrite
* Added a contributing section to our `rewrite-*` repos so that it's clearer for people to know how to get started.

I think this fixes the issues that were raised so I'll go ahead and close this. If you feel like I missed something or we should do more, please let me know ^_^
