### ISSUE TITLE
Please state defaults for optional parameters

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-docs#248]
GitHub actions make a good job explaining their parameters - and their default values.

Here, there is no list of default values.

Example: https://docs.openrewrite.org/recipes/java/logging/printstacktracetologerror.

I don't know if the Boolean default is true or false, what would be a really sensible value etc.

**Comment by timtebeek** [comment]
Agree that would be handy; the challenge is we don't set those defaults on the fields, so it's hard to have them available when we generate the documentation in [rewrite-recipe-markdown-generator](https://github.com/openrewrite/rewrite-recipe-markdown-generator). In a case like this one the default can be found by clicking on [the GitHub link, which shows it used further down](https://github.com/openrewrite/rewrite-logging-frameworks/blob/7b89f2708fa26ab717e9d8ae2745ed4cd205b418/src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java#L93). That's not optiomal of course, but figured that might help you for now.

**Comment by koppor** [comment]
Thank you for the hint.

I should have picked another example - I cannot quickly see the default `methodPattern` of https://docs.openrewrite.org/recipes/java/logging/parameterizedlogging

https://github.com/openrewrite/rewrite-logging-frameworks/blob/7b89f2708fa26ab717e9d8ae2745ed4cd205b418/src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java#L42

**Comment by timtebeek** [comment]
> I should have picked another example - I cannot quickly see the default `methodPattern` of https://docs.openrewrite.org/recipes/java/logging/parameterizedlogging

No worries; on that one there is no default value, as all options are required unless they are specifically marked as `required = false` & `@Nullable`. You should see a validation error when you do not pass in a `methodPattern`.

**Comment by mike-solomon** [comment]
Going to close this issue as I don't believe there is anything we can do to address this problem. I definitely understand the confusion -- but this is an underlying issue with how recipes are defined. Many recipes that have optional parameters do not have a "default" (as @timtebeek mentioned). For instance, an optional boolean is not really a "boolean" in the traditional sense. _Not_ providing true or false could actually result in the recipe producing something different than providing it with true or false. 

If there are particular recipes that you find confusing, I'd encourage you to submit a PR or open an issue in the GitHub repository where the recipe exists. We can update the descriptions of the parameters themselves to be clearer -- which would then carry over into the auto-generated docs. 

You can find the GitHub repository for any recipe by navigating to the recipe page in the docs and pressing the `GitHub` link. For the parameterized logging recipe, that exists in the [logging framework repository](https://github.com/openrewrite/rewrite-logging-frameworks). 

Hope that helps.
