### ISSUE TITLE
Expand refaster documentation

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-docs#256]
While we [have some basic documentation explaining what a Refaster recipe is](https://docs.openrewrite.org/authoring-recipes/types-of-recipes#refaster-templates), we don't provide enough information about how to get started with them or use them in projects. 

We should consider expanding our docs to provide additional context -- perhaps a getting started with refaster guide?

[Relevant community Slack link where this was requested](https://rewriteoss.slack.com/archives/C01A843MWG5/p1705236769587289)

**Comment by knutwannheden** [comment]
Please reach out to Tim or me if you need some answers to Refaster questions.
