### ISSUE TITLE
change group id and artifact id for gradle ?

### ISSUE THREAD

**Issue by Sanskarbajaj** [openrewrite/rewrite-docs#262]
like for maven we have something like this 
org.openrewrite.maven.ChangePluginGroupIdAndArtifactId

what if i want to use for gradle what can i use

**Comment by Sanskarbajaj** [comment]
Thanks @timtebeek :)

**Comment by Sanskarbajaj** [comment]
Hi @timtebeek  could you help me with this
    org.openrewrite.maven.ChangeManagedDependencyGroupIdAndArtifactId
this is something that we use for maven
whats for gradle?

**Comment by timtebeek** [comment]
There's no direct replacement for the Maven managed dependency recipe in Gradle (yet). You might want to open issue to describe what you're looking for. Perhaps you'd be interested in [adding Gradle dependency constraints](https://docs.gradle.org/current/userguide/dependency_constraints.html) for instance.
