### ISSUE TITLE
migrate log4jto slf4j

### ISSUE THREAD

**Issue by Sanskarbajaj** [openrewrite/rewrite-docs#265]
org.openrewrite.java.logging.slf4j.Log4jToSlf4j
when i'm using this recipie it says recipie not found other all recipies working fine in my gradle project.

**Comment by timtebeek** [comment]
Did you add the required dependency? Sounds like the recipe is not available to the plugin. The full config is here.
```groovy
plugins {
    id("org.openrewrite.rewrite") version("6.8.2")
}

rewrite {
    activeRecipe("org.openrewrite.java.logging.slf4j.Log4jToSlf4j")
}

repositories {
    mavenCentral()
}

` {
    rewrite("org.openrewrite.recipe:rewrite-logging-frameworks:2.4.3")
}
```
As per: https://docs.openrewrite.org/recipes/java/logging/slf4j/log4jtoslf4j

It looks like you're missing that `rewrite("org.openrewrite.recipe:rewrite-logging-frameworks:2.4.3")` under `dependencies { ... }`. Please double check and let me know if that helps.

I'll monitor for replies here but will close the issue already, as this isn't as much an issue with the docs but a question about the use. You're also welcome to ask questions via [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA).
