### ISSUE TITLE
Remove `JsonPathMatcher.encloses(Cursor c)` from JsonPathMatcher page

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#267]
As reported on Slack: https://rewriteoss.slack.com/archives/C01A843MWG5/p1713709042315309

The docs reference on [JsonPathMatcher](https://docs.openrewrite.org/reference/jsonpath-and-jsonpathmatcher-reference#authoring-recipes-with-jsonpathmatcher) mentions an JsonPathMatcher.encloses(Cursor c) method, however I don't find that in the implementation. Looks like there was a method back in 2022 that was removed.

https://github.com/openrewrite/rewrite-docs/blob/3ebe9769e90256e7c47a73252a7dca28dc816a05/reference/jsonpath-and-jsonpathmatcher-reference.md?plain=1#L123

**Comment by mike-solomon** [comment]
As part of this issue - I think we should do a review of this whole doc. Is it still accurate? Does JsonPathMatcher still exist and function the way it's described? Or is this just that one line that's wrong?

**Comment by timtebeek** [comment]
We still have multiple such classes for HCL, JSON and Yaml; I think it's just that one method that was removed. See for instance
https://github.com/openrewrite/rewrite/blob/main/rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
