### ISSUE TITLE
List recipes that produce data tables on a separate page

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#281]
## What problem are you trying to solve?
With the recent addition of data tables to the Maven plugin it's become more interesting to surface which recipes might produce data tables. Right now that information is shown on individual recipe pages, but that's not great for discovery.

## Describe the solution you'd like
Perhaps we could generate a separate page that lists all recipes that produce data tables, and link to that from the page that introduces data tables: https://docs.openrewrite.org/running-recipes/data-tables

That way folks are better able to find interesting recipes to run, and explore the results on their projects.

## Have you considered any alternatives or workarounds?
Right now it's possible to search for data tables and get a limited view into recipes that produce data tables, but you have to know what you're looking for, and there's no guarantees these are all recipes.
![image](https://github.com/openrewrite/rewrite-docs/assets/1027334/6afa81f2-fa42-4c3c-bed7-e119f043d7e3)

## Additional context
I'd hoped to link to such a page when answering questions, as it often helps to have a set of examples when implementing a new recipe to produce data tables.

**Comment by timtebeek** [comment]
cc @mike-solomon for visibility, as you don't appear to be [watching this repository](https://github.com/openrewrite/rewrite-docs/watchers) yet. No expectation that you'll prioritize this just yet; but could be helpful to keep in mind.

I'd thought of doing the same for recipe tags: have a page where folks can go to explore recipes for each particular tag.

**Comment by mike-solomon** [comment]
I've created a doc for this here: https://docs.openrewrite.org/reference/recipes-with-data-tables

Resolving!
