### ISSUE TITLE
Add `SetRange` to Supported dependency version selectors

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#298]
## What problem are you trying to solve?
We have a page listing various dependency version selectors
https://docs.openrewrite.org/reference/dependency-version-selectors

That page currently does not include our SetRange.
https://github.com/openrewrite/rewrite/blob/a98d83d698dda9971c93a0767b7f85d5866f306d/rewrite-core/src/main/java/org/openrewrite/semver/SetRange.java#L24-L30

Whereas we use that type of range here:
https://github.com/openrewrite/rewrite-spring/blob/062aa3b5ea1f9b082948a43e5d46e6b28a5df0f6/src/main/resources/META-INF/rewrite/spring-boot-20.yml#L153-L157

It's convenient when matching a particular range of dependencies, either including or excluding the start/end.

## Describe the solution you'd like
Add `SetRange` to 
https://github.com/openrewrite/rewrite-docs/blob/93527d3670b516c350faca901de7a0011e9e1cd2/reference/dependency-version-selectors.md?plain=1#L9

**Comment by mike-solomon** [comment]
@shanman190 If you have some time at some point - can you double-check that what I wrote in [this commit](https://github.com/openrewrite/rewrite-docs/commit/a3391ad312a78f6df203e7aa36e8ac695fa3f9f9) is correct? I'm assuming it is based on the rest of the doc - but I wasn't sure how to check if the latest version is used as the [tests only check if any particular version number is acceptable](https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/test/java/org/openrewrite/semver/SetRangeTest.java).

**Comment by shanman190** [comment]
@mike-solomon,

So the semver versions are constraint by two different traits. 

1. What are valid versions for the particular type (This is what each of the implementation's test classes are testing for)
2. Comparing versions with each other via `java.util.Comparator#compare` (via `VersionComparator`)

With `SetRange`, as you've noticed already it's allowing the mathematical set notation to be used to describe a set of versions that are acceptable, but then for the compare side utilizes the semantics of `LatestRelease` much like `HyphenRange` does. It's only when combined with `VersionComparator#upgrade` does the latest version come into view as it's an important quality for us to upgrade to the latest allowed from a version selector.
