### ISSUE TITLE
Finishing Checkstyle Docs 

### ISSUE THREAD

**Issue by SofiaBrittoSchwartz** [openrewrite/rewrite-docs#3]
The following Checkstyle docs need some work:

**SpansMultipleLines**
	- This file has very little that is done because it is non-standard in many ways. I know we're talking about moving this to another location in the docs, but something needs to be done to either hide it until we do that or make it look presentable.

**EmptyStatement**
	- This file doesn't have a complete explanation for the example portion.

**CovariantEquals**
	- This file doesn't have anything in the example explanation. It is the only file without something trying to explain the example.

**Comment by sambsnyd** [comment]
Finished the three docs outlined above in https://github.com/openrewrite/rewrite-docs/commit/56d60fc4d21e87df1eba663cc04b39dc1cb7f8d2
