### ISSUE TITLE
Fix workflow that warns about recipe pages

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-docs#310]
Recipe docs are automatically created via the markdown generator. We need to update the following GitHub workflow to let people know that when they attempt to open a PR against them. I thought I fixed that but probably messed up the regex: 

https://github.com/openrewrite/rewrite-docs/blob/master/.github/workflows/unneeded_recipe_updates.yml

**Comment by timtebeek** [comment]
Likely fixed by updating the path in https://github.com/openrewrite/rewrite-docs/commit/99e5554c922cec2ce6439281793b8c0b66cd83f5; Let's monitor and close if we see those comments posted.

**Comment by timtebeek** [comment]
Or on second thought; let's just presume it's fixed as we'll notice soon enough on any new PR.
