### ISSUE TITLE
Refaster credit

### ISSUE THREAD

**Issue by lowasser** [openrewrite/rewrite-docs#313]
Is there any chance that https://docs.openrewrite.org/authoring-recipes/refaster-recipes can at least briefly credit and link to [my 2013 paper outlining the concept](https://dl.acm.org/doi/10.1145/2541348.2541355) or [the original open-source Refaster whose annotations you use](https://errorprone.info/docs/refaster)?

I would've just sent a pull request, but I was struggling to wordsmith it a bit.

It looks like you have your own implementation which is pretty cool!

**Comment by sambsnyd** [comment]
Yes I agree that would be fair. I've pushed [this commit](https://github.com/openrewrite/rewrite-docs/commit/54b52874dbe8b53704197e509bf89759e3a0095a), adding the following text to the top of the article:


>[Refaster](https://errorprone.info/docs/refaster) is an open source refactoring technology unaffiliated with OpenRewrite, originally presented to the world by [Louis Wasserman in his 2013 paper](https://dl.acm.org/doi/10.1145/2541348.2541355). Refaster is easy to use and understand even for developers with no prior experience with parsers, compilers, or other refactoring tools. OpenRewrite has independently implemented support for Refaster-style templates so that recipe authors can benefit from Refaster's accessibility and existing catalogue of useful refactoring operations.

Hopefully that wordsmithing smiths right for you. If not happy to make adjustments. Cheers!

**Comment by sambsnyd** [comment]
Feel free to open a PR if you'd like to adjust the wording I've added. Also feel free to send me a message on our community slack, I would be happy to chat with you.

**Comment by lowasser** [comment]
Thanks, that sounds great!  I appreciate it.
