### ISSUE TITLE
Fix mobile logo

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-docs#316]
Right now, the OpenRewrite by Moderne logo is too big for mobile devices: 

![image](https://github.com/user-attachments/assets/82dd85bf-a349-49da-900f-c190d02effea)

I wonder if we can redesign the logo to be a bit more vertical? That or we just accept that mobile looks weird and close the issue.

**Comment by LindsayAuch** [comment]
@mike-solomon can you try this smaller version of the logo?[OpenRewritebyModerne.svg.zip](https://github.com/user-attachments/files/17637368/OpenRewritebyModerne.svg.zip)

**Comment by LindsayAuch** [comment]
@mike-solomon Maybe the stacked version will work better here. 

Can you try this svg?

[OpenRewritebyModernestacked.svg.zip](https://github.com/user-attachments/files/17648165/OpenRewritebyModernestacked.svg.zip)
<img width="432" alt="Screenshot 2024-11-06 at 9 03 30 AM" src="https://github.com/user-attachments/assets/ed8d8200-3e26-4a01-a77b-20d33dda8178">

**Comment by mike-solomon** [comment]
@LindsayAuch unfortunately that version is too difficult to read on desktop browsers >_< 

![image](https://github.com/user-attachments/assets/2449a91f-9440-44cc-a7cd-05a1698e835a)

**Comment by LindsayAuch** [comment]
Looking into Docusaurus, I see that it doesn’t provide separate mobile and desktop assets in the CSS by default. Instead, it uses media queries to handle responsiveness across screen sizes. 

**Mobile view:** When the screen width is less than 768px, the logo width is reduced to 220px and with less margin.
**Desktop view**: When the screen width is 768px or larger, the logo remains the same as the asset provided at 312 px. 

<img width="693" alt="Screenshot 2024-11-07 at 2 37 32 PM" src="https://github.com/user-attachments/assets/c4f0b1f8-eb54-4fdf-8445-d2ae79a3c7b7">

Here's an example of how you could style the logo differently for mobile and desktop:

`/* Custom styles for desktop (screens wider than 768px) */
@media (min-width: 768px) {
  .navbar__logo {
    width: 312px; /* Larger logo for desktop */
    margin-right: 20px;
  }
}

/* Custom styles for mobile (screens smaller than 768px) */
@media (max-width: 767px) {
  .navbar__logo {
    width: 220px; /* Smaller logo for mobile */
    margin-right: 10px;
  }
}
`

**Comment by mike-solomon** [comment]
Victory!! Thanks for the help @LindsayAuch 

![image](https://github.com/user-attachments/assets/c6a3f5ab-f424-4121-9796-5ba2064dbaec)
