### ISSUE TITLE
Docs: Group recipe descriptions into different types, ex java core, maven, xml, Junit5, Spring2, cleanup

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#41]
The list of recipe descriptions is very long now and it's hard to understand which groups of recipes we have now.

This is a pre-requisite for documenting specific guides for using dependency management recipes, SpringBoot migration, etc. These guides would point to their group of recipes rather than having to list them individually (and potentially drift when additional recipes are added to their group).

**Comment by gadams00** [comment]
https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/b104c7d165c8390a1ab85b5a1fcfce2cd4c82f3c
