### ISSUE TITLE
Docs: Recipe descriptions example yaml configuration

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#42]
Specifications/descriptions of recipes that contain options can be enhances by providing an example of how to configure this recipe in yaml.

**Comment by okundzich** [comment]
https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/1

**Comment by sambsnyd** [comment]
All recipe reference pages now have usage instructions showing how they can be configured in yaml and activated in the build plugins, including what dependency needs to be taken (if any).
