### ISSUE TITLE
Document usage of pointcut expressions

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#52]
Perhaps add links to external docs? Add this to all options that use pointcut expressions like change method.

**Comment by sambsnyd** [comment]
https://docs.openrewrite.org/v1beta/pointcut-expressions

**Comment by sambsnyd** [comment]
I've updated the recipe markdown generator to link the term "pointcut expression" in recipe argument descriptions to the doc page for the concept. 
https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/5ae4bdf54531f1f584203bed15d7dd5af8a1709f
