### ISSUE TITLE
Spring Boot 2.x docs has null in description

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#54]
<img width="1119" alt="Screen Shot 2021-06-27 at 10 14 41 AM" src="https://user-images.githubusercontent.com/26604045/123553549-cacdc700-d749-11eb-9378-19f65d8e2125.png">

**Comment by sambsnyd** [comment]
I'm pretty sure I've fixed this in code and it'll be gone next time we regenerate the docs, but I'll be sure to double check when we do
