### ISSUE TITLE
Docs: View recipe list as yaml

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-docs#55]
So people can add and exclude recipes from pre-built bundles. 

Point to https://docs.openrewrite.org/tutorials/authoring-declarative-yaml-recipes and https://docs.openrewrite.org/reference/yaml-format-reference to help users activate the recipe they will produce.

For example, ability to get this recipe list in the Spring Boot 2.x migration as yaml 

<img width="1154" alt="Screen Shot 2021-06-27 at 10 20 44 AM" src="https://user-images.githubusercontent.com/26604045/123553664-97d80300-d74a-11eb-8278-369eedaccf68.png">

**Comment by sambsnyd** [comment]
Done in https://github.com/openrewrite/rewrite-docs/commit/62ee4f2f98d7989196cf8b806bace39e85cbc740
