### ISSUE TITLE
Copy code not working on FF 93 / Linux and Windows

### ISSUE THREAD

**Issue by biergit** [openrewrite/rewrite-docs#70]
I've tried copying the code blocks from https://docs.openrewrite.org/tutorials/writing-a-java-refactoring-recipe by using the copy button on the top right corner as well as by manually selecting the text in the code block and trying to copy it with CTRL+C as well as with the browser context menu. Nothing works. With Chrome it works on Windows - Linux I didn't check.

**Comment by sambsnyd** [comment]
As a Firefox user, I've noticed the same. Unfortunately we don't have any direct control over that since we use [gitbook](https://www.gitbook.com/). Their latest update broke this. I've sent them a support request on this subject.

**Comment by sambsnyd** [comment]
Gitbook support responded to me saying they are aware of the issue and plan to fix it. They did not specify a time frame. Until then I recommend copying & pasting snippets out of this repository directly. Thanks for reporting this to us.
