### ISSUE TITLE
The next release of rewrite-maven-plugin will support runNoFork and dryRunNoFork

### ISSUE THREAD

**Issue by ao-apps** [openrewrite/rewrite-docs#82]
Per issue https://github.com/openrewrite/rewrite-maven-plugin/issues/331 the next release of rewrite-maven-plugin will support runNoFork and dryRunNoFork.

Please update the documentation for "executions" from "dryRun" to "dryRunNoFork".

https://github.com/openrewrite/rewrite-docs/blob/master/reference/rewrite-maven-plugin.md

**Comment by tkvangorder** [comment]
The documents have been updated to include the new goals.

**Comment by ao-apps** [comment]
Thank you very much.
