### ISSUE TITLE
Link to Methods Patterns give a 404

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-docs#84]
I was on [this](https://docs.openrewrite.org/reference/recipes/java/changemethodtargettostatic) page and the link [method-patterns](https://github.com/openrewrite/rewrite-docs/blob/master/reference/method-patterns.md) gives me a 404 as it links to [README.md](https://github.com/openrewrite/rewrite-docs/blob/master/reference/method-patterns/README.md) instead of [method-patterns.md](https://github.com/openrewrite/rewrite-docs/blob/master/reference/method-patterns.md)

**Comment by rdifrango** [comment]
@pway happy to submit a PR here if it's simply changing the `[method pattern](/reference/method-patterns)` to `[method pattern](/reference/method-patterns.md)`

**Comment by pway99** [comment]
Thanks @rdifrango,  did not see your offer before modifying the docs.   Just for future reference, the fix also required a modification to the rewrite-recipe-markdown-generator also.
