### ISSUE TITLE
Links to `rewrite-roadmap` lead to 404

### ISSUE THREAD

**Issue by dgroomes** [openrewrite/rewrite-docs#90]
## Expected Behavior

When I click the <https://github.com/openrewrite/rewrite-roadmap/issues/7> link that's referenced in the [Getting Started page](https://docs.openrewrite.org/getting-started/getting-started) it should lead to the OpenRewrite roadmap.

## Actual Behavior

When I click the link, it leads to a 404 page on GitHub.

## More info

There are various links to <https://github.com/openrewrite/rewrite-roadmap/issues>. Here is a GitHub search that shows the places: <https://github.com/openrewrite/rewrite-docs/search?q=roadmap>. I looked briefly and couldn't find if the roadmap is at a new home, or is private. In any case, it's a small thing. Thanks!

**Comment by okundzich** [comment]
Thanks for reporting! We will remove the links as we removed the roadmap as a separate project board. 

The Gradle support is in the works if that's what you are looking for.  We will also be expanding our language support to Python, TypeScript and C# in the next few quarters.

**Comment by dgroomes** [comment]
Great, thank you Olga! I'm looking forward to new features and exploring all the existing functionality too.

**Comment by tkvangorder** [comment]
The docs have been updated to remove the link to `rewrite-roadmap`, thanks for reporting the issue!
